import Service from '@ember/service';
import { tracked } from '@glimmer/tracking';

export default class TimezoneService extends Service {
  @tracked names = [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Addis Ababa',
    'Africa/Algiers',
    'Africa/Asmara',
    'Africa/Bissau',
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Dar es Salaam',
    'Africa/Djibouti',
    'Africa/El Aaiun',
    'Africa/Johannesburg',
    'Africa/Kampala',
    'Africa/Khartoum',
    'Africa/Lagos',
    'Africa/Maputo',
    'Africa/Mogadishu',
    'Africa/Monrovia',
    'Africa/Nairobi',
    'Africa/Ndjamena',
    'Africa/Tripoli',
    'Africa/Tunis',
    'Africa/Windhoek',
    'America/Antigua',
    'America/Argentina',
    'America/Asuncion',
    'America/Barbados',
    'America/Belize',
    'America/Bogota',
    'America/Caracas',
    'America/Cayman',
    'America/Costa Rica',
    'America/Curacao',
    'America/El Salvador',
    'America/Grand Turk',
    'America/Guatemala',
    'America/Guayaquil',
    'America/Guyana',
    'America/Havana',
    'America/Jamaica',
    'America/La Paz',
    'America/Lima',
    'America/Managua',
    'America/Mexico City',
    'America/Miquelon',
    'America/Montevideo',
    'America/Nassau',
    'America/New York',
    'America/Panama',
    'America/Paramaribo',
    'America/Port of Spain',
    'America/Port-au-Prince',
    'America/Santiago',
    'America/Sao Paulo',
    'America/Tegucigalpa',
    'America/Toronto',
    'Antarctica/Troll',
    'Asia/Aden',
    'Asia/Almaty',
    'Asia/Amman',
    'Asia/Ashgabat',
    'Asia/Baghdad',
    'Asia/Bahrain',
    'Asia/Baku',
    'Asia/Bangkok',
    'Asia/Beirut',
    'Asia/Bishkek',
    'Asia/Brunei',
    'Asia/Colombo',
    'Asia/Damascus',
    'Asia/Dhaka',
    'Asia/Dili',
    'Asia/Dubai',
    'Asia/Dushanbe',
    'Asia/Hebron',
    'Asia/Ho Chi Minh',
    'Asia/Hong Kong',
    'Asia/Jakarta',
    'Asia/Jerusalem',
    'Asia/Kabul',
    'Asia/Karachi',
    'Asia/Kathmandu',
    'Asia/Kolkata',
    'Asia/Kuala Lumpur',
    'Asia/Kuwait',
    'Asia/Macau',
    'Asia/Manila',
    'Asia/Muscat',
    'Asia/Nicosia',
    'Asia/Phnom Penh',
    'Asia/Pyongyang',
    'Asia/Qatar',
    'Asia/Riyadh',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Taipei',
    'Asia/Tashkent',
    'Asia/Tbilisi',
    'Asia/Tehran',
    'Asia/Thimphu',
    'Asia/Tokyo',
    'Asia/Ulaanbaatar',
    'Asia/Vientiane',
    'Asia/Yerevan',
    'Atlantic/Bermuda',
    'Atlantic/Cape Verde',
    'Atlantic/Faroe',
    'Atlantic/Reykjavik',
    'Atlantic/Stanley',
    'Australia/Sydney',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Athens',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Chisinau',
    'Europe/Copenhagen',
    'Europe/Dublin',
    'Europe/Gibraltar',
    'Europe/Helsinki',
    'Europe/Istanbul',
    'Europe/Kyiv',
    'Europe/Lisbon',
    'Europe/London',
    'Europe/Luxembourg',
    'Europe/Madrid',
    'Europe/Malta',
    'Europe/Minsk',
    'Europe/Monaco',
    'Europe/Moscow',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Prague',
    'Europe/Riga',
    'Europe/Rome',
    'Europe/Sofia',
    'Europe/Stockholm',
    'Europe/Tallinn',
    'Europe/Tirane',
    'Europe/Vienna',
    'Europe/Vilnius',
    'Europe/Warsaw',
    'Europe/Zurich',
    'Indian/Antananarivo',
    'Indian/Chagos',
    'Indian/Christmas',
    'Indian/Cocos',
    'Indian/Comoro',
    'Indian/Mahe',
    'Indian/Maldives',
    'Indian/Mauritius',
    'Indian/Mayotte',
    'Indian/Reunion',
    'Pacific/Apia',
    'Pacific/Auckland',
    'Pacific/Efate',
    'Pacific/Fakaofo',
    'Pacific/Fiji',
    'Pacific/Funafuti',
    'Pacific/Guadalcanal',
    'Pacific/Guam',
    'Pacific/Majuro',
    'Pacific/Nauru',
    'Pacific/Niue',
    'Pacific/Noumea',
    'Pacific/Pago Pago',
    'Pacific/Palau',
    'Pacific/Pitcairn',
    'Pacific/Pohnpei',
    'Pacific/Port Moresby',
    'Pacific/Rarotonga',
    'Pacific/Saipan',
    'Pacific/Tahiti',
    'Pacific/Tarawa',
    'Pacific/Tongatapu',
    'Pacific/Wallis',
  ];
}
